name: Hung Chen
markdown: redcarpet
pygments: true
github: https://www.github.com/loahou04
about: I am a developer who likes to dabble in a little bit of everything.  
urls:
    - text: github
      url: https://github.com/loahou04
    - text: email
      url: mailto:hung.chen@tindersln.com
